--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 19/11/2021 9:35:55 PM
-- Server version: 8.0.26
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE aims;

--
-- Drop table `book_20183534_nguyenvanhieu`
--
DROP TABLE IF EXISTS book_20183534_nguyenvanhieu;

--
-- Drop table `cd_20183534_nguyenvanhieu`
--
DROP TABLE IF EXISTS cd_20183534_nguyenvanhieu;

--
-- Drop table `dvd_20183534_nguyenvanhieu`
--
DROP TABLE IF EXISTS dvd_20183534_nguyenvanhieu;

--
-- Drop table `ordermedia_20183534_nguyenvanhieu`
--
DROP TABLE IF EXISTS ordermedia_20183534_nguyenvanhieu;

--
-- Drop table `media_20183534_nguyenvanhieu`
--
DROP TABLE IF EXISTS media_20183534_nguyenvanhieu;

--
-- Drop table `paymenttransaction_20183534_nguyenvanhieu`
--
DROP TABLE IF EXISTS paymenttransaction_20183534_nguyenvanhieu;

--
-- Drop table `card_20183534_nguyenvanhieu`
--
DROP TABLE IF EXISTS card_20183534_nguyenvanhieu;

--
-- Drop table `invoice_20183534_nguyenvanhieu`
--
DROP TABLE IF EXISTS invoice_20183534_nguyenvanhieu;

--
-- Drop table `order_20183534_nguyenvanhieu`
--
DROP TABLE IF EXISTS order_20183534_nguyenvanhieu;

--
-- Drop table `deliveryinfo_20183534_nguyenvanhieu`
--
DROP TABLE IF EXISTS deliveryinfo_20183534_nguyenvanhieu;

--
-- Set default database
--
USE aims;

--
-- Create table `deliveryinfo_20183534_nguyenvanhieu`
--
CREATE TABLE deliveryinfo_20183534_nguyenvanhieu (
  id int NOT NULL,
  name varchar(45) DEFAULT NULL,
  province varchar(45) DEFAULT NULL,
  instructions varchar(200) DEFAULT NULL,
  address varchar(100) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `order_20183534_nguyenvanhieu`
--
CREATE TABLE order_20183534_nguyenvanhieu (
  id int NOT NULL AUTO_INCREMENT,
  shippingFees varchar(45) DEFAULT NULL,
  deliveryInfoId int DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE order_20183534_nguyenvanhieu
ADD CONSTRAINT FK_order_deliveryinfo_id FOREIGN KEY (deliveryInfoId)
REFERENCES deliveryinfo_20183534_nguyenvanhieu (id);

--
-- Create table `invoice_20183534_nguyenvanhieu`
--
CREATE TABLE invoice_20183534_nguyenvanhieu (
  id int NOT NULL AUTO_INCREMENT,
  totalAmount int DEFAULT NULL,
  orderId int DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE invoice_20183534_nguyenvanhieu
ADD CONSTRAINT FK_invoice_order_id FOREIGN KEY (orderId)
REFERENCES order_20183534_nguyenvanhieu (id);

--
-- Create table `card_20183534_nguyenvanhieu`
--
CREATE TABLE card_20183534_nguyenvanhieu (
  id int NOT NULL,
  cardCode varchar(15) DEFAULT NULL,
  owner varchar(45) DEFAULT NULL,
  cvvCode varchar(3) DEFAULT NULL,
  dateExpired varchar(4) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `paymenttransaction_20183534_nguyenvanhieu`
--
CREATE TABLE paymenttransaction_20183534_nguyenvanhieu (
  id int NOT NULL AUTO_INCREMENT,
  createAt datetime DEFAULT NULL,
  content varchar(45) DEFAULT NULL,
  method varchar(45) DEFAULT NULL,
  cardId int DEFAULT NULL,
  InvoiceId int DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE paymenttransaction_20183534_nguyenvanhieu
ADD CONSTRAINT FK_paymenttransaction_card_id FOREIGN KEY (cardId)
REFERENCES card_20183534_nguyenvanhieu (id);

--
-- Create foreign key
--
ALTER TABLE paymenttransaction_20183534_nguyenvanhieu
ADD CONSTRAINT FK_paymenttransaction_invoice_id FOREIGN KEY (InvoiceId)
REFERENCES invoice_20183534_nguyenvanhieu (id);

--
-- Create table `media_20183534_nguyenvanhieu`
--
CREATE TABLE media_20183534_nguyenvanhieu (
  id int NOT NULL AUTO_INCREMENT,
  category varchar(45) DEFAULT NULL,
  price decimal(19, 2) DEFAULT NULL,
  quantity smallint DEFAULT NULL,
  title varchar(45) DEFAULT NULL,
  value varchar(255) DEFAULT NULL,
  imageUrl varchar(45) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `ordermedia_20183534_nguyenvanhieu`
--
CREATE TABLE ordermedia_20183534_nguyenvanhieu (
  orderId int NOT NULL,
  price int DEFAULT NULL,
  quantity int DEFAULT NULL,
  mediaId int NOT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE ordermedia_20183534_nguyenvanhieu
ADD CONSTRAINT FK_ordermedia_media_id FOREIGN KEY (mediaId)
REFERENCES media_20183534_nguyenvanhieu (id);

--
-- Create foreign key
--
ALTER TABLE ordermedia_20183534_nguyenvanhieu
ADD CONSTRAINT FK_ordermedia_order_id FOREIGN KEY (orderId)
REFERENCES order_20183534_nguyenvanhieu (id);

--
-- Create table `dvd_20183534_nguyenvanhieu`
--
CREATE TABLE dvd_20183534_nguyenvanhieu (
  id int NOT NULL,
  discType varchar(45) DEFAULT NULL,
  director varchar(45) DEFAULT NULL,
  runtime int DEFAULT NULL,
  studio varchar(45) DEFAULT NULL,
  subtitle varchar(45) DEFAULT NULL,
  releasedDate datetime DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE dvd_20183534_nguyenvanhieu
ADD CONSTRAINT FK_dvd_media_id FOREIGN KEY (id)
REFERENCES media_20183534_nguyenvanhieu (id);

--
-- Create table `cd_20183534_nguyenvanhieu`
--
CREATE TABLE cd_20183534_nguyenvanhieu (
  id int NOT NULL,
  artist varchar(45) DEFAULT NULL,
  recordLabel varchar(45) DEFAULT NULL,
  musicType varchar(45) DEFAULT NULL,
  releaseDate date DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE cd_20183534_nguyenvanhieu
ADD CONSTRAINT FK_cd_media_id FOREIGN KEY (id)
REFERENCES media_20183534_nguyenvanhieu (id);

--
-- Create table `book_20183534_nguyenvanhieu`
--
CREATE TABLE book_20183534_nguyenvanhieu (
  id int NOT NULL,
  author varchar(45) DEFAULT NULL,
  coverType varchar(45) DEFAULT NULL,
  publisher varchar(45) DEFAULT NULL,
  publishDate datetime DEFAULT NULL,
  numOfPages int DEFAULT NULL,
  language varchar(45) DEFAULT NULL,
  bookCategory varchar(45) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE book_20183534_nguyenvanhieu
ADD CONSTRAINT FK_book_media_id FOREIGN KEY (id)
REFERENCES media_20183534_nguyenvanhieu (id);

-- 
-- Dumping data for table deliveryinfo_20183534_nguyenvanhieu
--
-- Table aims.deliveryinfo_20183534_nguyenvanhieu does not contain any data (it is empty)

-- 
-- Dumping data for table order_20183534_nguyenvanhieu
--
-- Table aims.order_20183534_nguyenvanhieu does not contain any data (it is empty)

-- 
-- Dumping data for table invoice_20183534_nguyenvanhieu
--
-- Table aims.invoice_20183534_nguyenvanhieu does not contain any data (it is empty)

-- 
-- Dumping data for table card_20183534_nguyenvanhieu
--
-- Table aims.card_20183534_nguyenvanhieu does not contain any data (it is empty)

-- 
-- Dumping data for table media_20183534_nguyenvanhieu
--
-- Table aims.media_20183534_nguyenvanhieu does not contain any data (it is empty)

-- 
-- Dumping data for table paymenttransaction_20183534_nguyenvanhieu
--
-- Table aims.paymenttransaction_20183534_nguyenvanhieu does not contain any data (it is empty)

-- 
-- Dumping data for table ordermedia_20183534_nguyenvanhieu
--
-- Table aims.ordermedia_20183534_nguyenvanhieu does not contain any data (it is empty)

-- 
-- Dumping data for table dvd_20183534_nguyenvanhieu
--
-- Table aims.dvd_20183534_nguyenvanhieu does not contain any data (it is empty)

-- 
-- Dumping data for table cd_20183534_nguyenvanhieu
--
-- Table aims.cd_20183534_nguyenvanhieu does not contain any data (it is empty)

-- 
-- Dumping data for table book_20183534_nguyenvanhieu
--
-- Table aims.book_20183534_nguyenvanhieu does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;